"""Added academic year and dept for bulk upload

Revision ID: 94b965185120
Revises: 67933e5947e9
Create Date: 2026-02-24 23:39:09.382146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b965185120'
down_revision = '67933e5947e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('academic_year', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('academic_year')
        batch_op.drop_column('phone')

    with op.batch_alter_table('team_members', schema=None) as batch_op:
        batch_op.drop_column('department')
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
